//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from GolightSemantico.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace analyzer {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="GolightSemanticoParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IGolightSemanticoVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by the <c>program</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.casos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] GolightSemanticoParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>contenido</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.casos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitContenido([NotNull] GolightSemanticoParser.ContenidoContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>bloque</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.bloqueindependiente"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBloque([NotNull] GolightSemanticoParser.BloqueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>funcionvacia</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.funciones"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncionvacia([NotNull] GolightSemanticoParser.FuncionvaciaContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>funcionconparametros</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.funciones"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncionconparametros([NotNull] GolightSemanticoParser.FuncionconparametrosContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>funcionanonima</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.funciones"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncionanonima([NotNull] GolightSemanticoParser.FuncionanonimaContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>parametros</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.casos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParametros([NotNull] GolightSemanticoParser.ParametrosContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>declaracionslicevalor</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.declaracion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaracionslicevalor([NotNull] GolightSemanticoParser.DeclaracionslicevalorContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>declaexplicitavalor</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.declaracion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaexplicitavalor([NotNull] GolightSemanticoParser.DeclaexplicitavalorContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>declaexplicitanovalor</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.declaracion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaexplicitanovalor([NotNull] GolightSemanticoParser.DeclaexplicitanovalorContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>declaracionslicenovalor</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.declaracion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaracionslicenovalor([NotNull] GolightSemanticoParser.DeclaracionslicenovalorContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>declaracionimplicita</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.declaracion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaracionimplicita([NotNull] GolightSemanticoParser.DeclaracionimplicitaContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>declaracionimplicitaslice</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.declaracion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaracionimplicitaslice([NotNull] GolightSemanticoParser.DeclaracionimplicitasliceContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>asignacionslicesimple</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.declaracion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAsignacionslicesimple([NotNull] GolightSemanticoParser.AsignacionslicesimpleContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>asignacionmetodos</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.declaracion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAsignacionmetodos([NotNull] GolightSemanticoParser.AsignacionmetodosContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>asignacionstruct</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.declaracion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAsignacionstruct([NotNull] GolightSemanticoParser.AsignacionstructContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>asignacion</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.declaracion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAsignacion([NotNull] GolightSemanticoParser.AsignacionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>asignaciondesdefuncion</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.declaracion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAsignaciondesdefuncion([NotNull] GolightSemanticoParser.AsignaciondesdefuncionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>slices</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.casos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSlices([NotNull] GolightSemanticoParser.SlicesContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>multdivmod</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultdivmod([NotNull] GolightSemanticoParser.MultdivmodContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>incredecr</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIncredecr([NotNull] GolightSemanticoParser.IncredecrContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>or</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOr([NotNull] GolightSemanticoParser.OrContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>valoresexpr</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValoresexpr([NotNull] GolightSemanticoParser.ValoresexprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>llamadafuncion1</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLlamadafuncion1([NotNull] GolightSemanticoParser.Llamadafuncion1Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>valorexpr</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValorexpr([NotNull] GolightSemanticoParser.ValorexprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>nativas</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNativas([NotNull] GolightSemanticoParser.NativasContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>igualdad</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIgualdad([NotNull] GolightSemanticoParser.IgualdadContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>asignacionfor</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAsignacionfor([NotNull] GolightSemanticoParser.AsignacionforContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expdotexp</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpdotexp([NotNull] GolightSemanticoParser.ExpdotexpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>relacionales</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelacionales([NotNull] GolightSemanticoParser.RelacionalesContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>slicesdesc</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSlicesdesc([NotNull] GolightSemanticoParser.SlicesdescContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>corchetesexpre</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCorchetesexpre([NotNull] GolightSemanticoParser.CorchetesexpreContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>unario</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnario([NotNull] GolightSemanticoParser.UnarioContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>parentesisexpre</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParentesisexpre([NotNull] GolightSemanticoParser.ParentesisexpreContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>sumres</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSumres([NotNull] GolightSemanticoParser.SumresContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>and</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnd([NotNull] GolightSemanticoParser.AndContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>llamadafuncion2</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLlamadafuncion2([NotNull] GolightSemanticoParser.Llamadafuncion2Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>id</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitId([NotNull] GolightSemanticoParser.IdContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expdotexp1</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpdotexp1([NotNull] GolightSemanticoParser.Expdotexp1Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>println</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.casos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrintln([NotNull] GolightSemanticoParser.PrintlnContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>atoi</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.funcionesnativas"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAtoi([NotNull] GolightSemanticoParser.AtoiContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>parsefloat</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.funcionesnativas"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParsefloat([NotNull] GolightSemanticoParser.ParsefloatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>typeof</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.funcionesnativas"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeof([NotNull] GolightSemanticoParser.TypeofContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>index</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.funcionesnativas"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndex([NotNull] GolightSemanticoParser.IndexContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>join</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.funcionesnativas"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJoin([NotNull] GolightSemanticoParser.JoinContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>len</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.funcionesnativas"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLen([NotNull] GolightSemanticoParser.LenContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>append</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.funcionesnativas"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAppend([NotNull] GolightSemanticoParser.AppendContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>incremento</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.incredecre"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIncremento([NotNull] GolightSemanticoParser.IncrementoContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>decremento</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.incredecre"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDecremento([NotNull] GolightSemanticoParser.DecrementoContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>incremento2</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.incredecre"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIncremento2([NotNull] GolightSemanticoParser.Incremento2Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>decremento2</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.incredecre"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDecremento2([NotNull] GolightSemanticoParser.Decremento2Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>secuenciascontrol</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.casos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSecuenciascontrol([NotNull] GolightSemanticoParser.SecuenciascontrolContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>if1</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.if"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIf1([NotNull] GolightSemanticoParser.If1Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>elseif</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.if"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElseif([NotNull] GolightSemanticoParser.ElseifContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>else</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.if"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElse([NotNull] GolightSemanticoParser.ElseContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>switch</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.casos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitch([NotNull] GolightSemanticoParser.SwitchContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>case</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.casos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCase([NotNull] GolightSemanticoParser.CaseContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>default</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.casos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDefault([NotNull] GolightSemanticoParser.DefaultContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>for1</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.for"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFor1([NotNull] GolightSemanticoParser.For1Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>for2</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.for"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFor2([NotNull] GolightSemanticoParser.For2Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>for3</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.for"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFor3([NotNull] GolightSemanticoParser.For3Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>break</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.sentenciastransferencia"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBreak([NotNull] GolightSemanticoParser.BreakContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>continue</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.sentenciastransferencia"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitContinue([NotNull] GolightSemanticoParser.ContinueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>return</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.sentenciastransferencia"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturn([NotNull] GolightSemanticoParser.ReturnContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>struct1</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.struct"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStruct1([NotNull] GolightSemanticoParser.Struct1Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>struct2</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.struct"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStruct2([NotNull] GolightSemanticoParser.Struct2Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>struct3</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.struct"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStruct3([NotNull] GolightSemanticoParser.Struct3Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>camposstruct1</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.campostruct"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCamposstruct1([NotNull] GolightSemanticoParser.Camposstruct1Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>instanciacionstruct</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.campostruct"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstanciacionstruct([NotNull] GolightSemanticoParser.InstanciacionstructContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>valores</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.casos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValores([NotNull] GolightSemanticoParser.ValoresContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>int</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.valor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInt([NotNull] GolightSemanticoParser.IntContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>float64</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.valor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFloat64([NotNull] GolightSemanticoParser.Float64Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>string</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.valor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString([NotNull] GolightSemanticoParser.StringContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>bool</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.valor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBool([NotNull] GolightSemanticoParser.BoolContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>rune</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.valor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRune([NotNull] GolightSemanticoParser.RuneContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>null</c>
	/// labeled alternative in <see cref="GolightSemanticoParser.valor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNull([NotNull] GolightSemanticoParser.NullContext context);
}
} // namespace analyzer
