//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Golight.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace analyzer {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="GolightParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IGolightVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by the <c>program</c>
	/// labeled alternative in <see cref="GolightParser.casos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] GolightParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>contenido</c>
	/// labeled alternative in <see cref="GolightParser.casos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitContenido([NotNull] GolightParser.ContenidoContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>bloque</c>
	/// labeled alternative in <see cref="GolightParser.bloqueindependiente"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBloque([NotNull] GolightParser.BloqueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>funcionvacia</c>
	/// labeled alternative in <see cref="GolightParser.funciones"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncionvacia([NotNull] GolightParser.FuncionvaciaContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>funcionconparametros</c>
	/// labeled alternative in <see cref="GolightParser.funciones"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncionconparametros([NotNull] GolightParser.FuncionconparametrosContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>funcionanonima</c>
	/// labeled alternative in <see cref="GolightParser.funciones"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncionanonima([NotNull] GolightParser.FuncionanonimaContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>parametros</c>
	/// labeled alternative in <see cref="GolightParser.casos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParametros([NotNull] GolightParser.ParametrosContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>declaracionslicevalor</c>
	/// labeled alternative in <see cref="GolightParser.declaracion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaracionslicevalor([NotNull] GolightParser.DeclaracionslicevalorContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>declaexplicitavalor</c>
	/// labeled alternative in <see cref="GolightParser.declaracion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaexplicitavalor([NotNull] GolightParser.DeclaexplicitavalorContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>declaexplicitanovalor</c>
	/// labeled alternative in <see cref="GolightParser.declaracion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaexplicitanovalor([NotNull] GolightParser.DeclaexplicitanovalorContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>declaracionslicenovalor</c>
	/// labeled alternative in <see cref="GolightParser.declaracion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaracionslicenovalor([NotNull] GolightParser.DeclaracionslicenovalorContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>declaracionimplicita</c>
	/// labeled alternative in <see cref="GolightParser.declaracion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaracionimplicita([NotNull] GolightParser.DeclaracionimplicitaContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>declaracionimplicitaslice</c>
	/// labeled alternative in <see cref="GolightParser.declaracion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaracionimplicitaslice([NotNull] GolightParser.DeclaracionimplicitasliceContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>asignacionslicesimple</c>
	/// labeled alternative in <see cref="GolightParser.declaracion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAsignacionslicesimple([NotNull] GolightParser.AsignacionslicesimpleContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>asignacionmetodos</c>
	/// labeled alternative in <see cref="GolightParser.declaracion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAsignacionmetodos([NotNull] GolightParser.AsignacionmetodosContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>asignacionstruct</c>
	/// labeled alternative in <see cref="GolightParser.declaracion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAsignacionstruct([NotNull] GolightParser.AsignacionstructContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>asignacion</c>
	/// labeled alternative in <see cref="GolightParser.declaracion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAsignacion([NotNull] GolightParser.AsignacionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>asignaciondesdefuncion</c>
	/// labeled alternative in <see cref="GolightParser.declaracion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAsignaciondesdefuncion([NotNull] GolightParser.AsignaciondesdefuncionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>slices</c>
	/// labeled alternative in <see cref="GolightParser.casos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSlices([NotNull] GolightParser.SlicesContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>multdivmod</c>
	/// labeled alternative in <see cref="GolightParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultdivmod([NotNull] GolightParser.MultdivmodContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>incredecr</c>
	/// labeled alternative in <see cref="GolightParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIncredecr([NotNull] GolightParser.IncredecrContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>or</c>
	/// labeled alternative in <see cref="GolightParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOr([NotNull] GolightParser.OrContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>valoresexpr</c>
	/// labeled alternative in <see cref="GolightParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValoresexpr([NotNull] GolightParser.ValoresexprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>llamadafuncion1</c>
	/// labeled alternative in <see cref="GolightParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLlamadafuncion1([NotNull] GolightParser.Llamadafuncion1Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>valorexpr</c>
	/// labeled alternative in <see cref="GolightParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValorexpr([NotNull] GolightParser.ValorexprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>nativas</c>
	/// labeled alternative in <see cref="GolightParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNativas([NotNull] GolightParser.NativasContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>igualdad</c>
	/// labeled alternative in <see cref="GolightParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIgualdad([NotNull] GolightParser.IgualdadContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>asignacionfor</c>
	/// labeled alternative in <see cref="GolightParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAsignacionfor([NotNull] GolightParser.AsignacionforContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expdotexp</c>
	/// labeled alternative in <see cref="GolightParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpdotexp([NotNull] GolightParser.ExpdotexpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>relacionales</c>
	/// labeled alternative in <see cref="GolightParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelacionales([NotNull] GolightParser.RelacionalesContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>slicesdesc</c>
	/// labeled alternative in <see cref="GolightParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSlicesdesc([NotNull] GolightParser.SlicesdescContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>corchetesexpre</c>
	/// labeled alternative in <see cref="GolightParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCorchetesexpre([NotNull] GolightParser.CorchetesexpreContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>unario</c>
	/// labeled alternative in <see cref="GolightParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnario([NotNull] GolightParser.UnarioContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>parentesisexpre</c>
	/// labeled alternative in <see cref="GolightParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParentesisexpre([NotNull] GolightParser.ParentesisexpreContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>sumres</c>
	/// labeled alternative in <see cref="GolightParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSumres([NotNull] GolightParser.SumresContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>and</c>
	/// labeled alternative in <see cref="GolightParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnd([NotNull] GolightParser.AndContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>llamadafuncion2</c>
	/// labeled alternative in <see cref="GolightParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLlamadafuncion2([NotNull] GolightParser.Llamadafuncion2Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>id</c>
	/// labeled alternative in <see cref="GolightParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitId([NotNull] GolightParser.IdContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expdotexp1</c>
	/// labeled alternative in <see cref="GolightParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpdotexp1([NotNull] GolightParser.Expdotexp1Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>println</c>
	/// labeled alternative in <see cref="GolightParser.casos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrintln([NotNull] GolightParser.PrintlnContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>atoi</c>
	/// labeled alternative in <see cref="GolightParser.funcionesnativas"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAtoi([NotNull] GolightParser.AtoiContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>parsefloat</c>
	/// labeled alternative in <see cref="GolightParser.funcionesnativas"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParsefloat([NotNull] GolightParser.ParsefloatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>typeof</c>
	/// labeled alternative in <see cref="GolightParser.funcionesnativas"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeof([NotNull] GolightParser.TypeofContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>index</c>
	/// labeled alternative in <see cref="GolightParser.funcionesnativas"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndex([NotNull] GolightParser.IndexContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>join</c>
	/// labeled alternative in <see cref="GolightParser.funcionesnativas"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJoin([NotNull] GolightParser.JoinContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>len</c>
	/// labeled alternative in <see cref="GolightParser.funcionesnativas"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLen([NotNull] GolightParser.LenContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>append</c>
	/// labeled alternative in <see cref="GolightParser.funcionesnativas"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAppend([NotNull] GolightParser.AppendContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>incremento</c>
	/// labeled alternative in <see cref="GolightParser.incredecre"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIncremento([NotNull] GolightParser.IncrementoContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>decremento</c>
	/// labeled alternative in <see cref="GolightParser.incredecre"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDecremento([NotNull] GolightParser.DecrementoContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>incremento2</c>
	/// labeled alternative in <see cref="GolightParser.incredecre"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIncremento2([NotNull] GolightParser.Incremento2Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>decremento2</c>
	/// labeled alternative in <see cref="GolightParser.incredecre"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDecremento2([NotNull] GolightParser.Decremento2Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>secuenciascontrol</c>
	/// labeled alternative in <see cref="GolightParser.casos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSecuenciascontrol([NotNull] GolightParser.SecuenciascontrolContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>if1</c>
	/// labeled alternative in <see cref="GolightParser.if"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIf1([NotNull] GolightParser.If1Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>elseif</c>
	/// labeled alternative in <see cref="GolightParser.if"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElseif([NotNull] GolightParser.ElseifContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>else</c>
	/// labeled alternative in <see cref="GolightParser.if"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElse([NotNull] GolightParser.ElseContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>switch</c>
	/// labeled alternative in <see cref="GolightParser.casos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitch([NotNull] GolightParser.SwitchContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>case</c>
	/// labeled alternative in <see cref="GolightParser.casos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCase([NotNull] GolightParser.CaseContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>default</c>
	/// labeled alternative in <see cref="GolightParser.casos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDefault([NotNull] GolightParser.DefaultContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>for1</c>
	/// labeled alternative in <see cref="GolightParser.for"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFor1([NotNull] GolightParser.For1Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>for2</c>
	/// labeled alternative in <see cref="GolightParser.for"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFor2([NotNull] GolightParser.For2Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>for3</c>
	/// labeled alternative in <see cref="GolightParser.for"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFor3([NotNull] GolightParser.For3Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>break</c>
	/// labeled alternative in <see cref="GolightParser.sentenciastransferencia"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBreak([NotNull] GolightParser.BreakContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>continue</c>
	/// labeled alternative in <see cref="GolightParser.sentenciastransferencia"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitContinue([NotNull] GolightParser.ContinueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>return</c>
	/// labeled alternative in <see cref="GolightParser.sentenciastransferencia"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturn([NotNull] GolightParser.ReturnContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>valores</c>
	/// labeled alternative in <see cref="GolightParser.casos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValores([NotNull] GolightParser.ValoresContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>int</c>
	/// labeled alternative in <see cref="GolightParser.valor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInt([NotNull] GolightParser.IntContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>float64</c>
	/// labeled alternative in <see cref="GolightParser.valor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFloat64([NotNull] GolightParser.Float64Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>string</c>
	/// labeled alternative in <see cref="GolightParser.valor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString([NotNull] GolightParser.StringContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>bool</c>
	/// labeled alternative in <see cref="GolightParser.valor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBool([NotNull] GolightParser.BoolContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>rune</c>
	/// labeled alternative in <see cref="GolightParser.valor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRune([NotNull] GolightParser.RuneContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>null</c>
	/// labeled alternative in <see cref="GolightParser.valor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNull([NotNull] GolightParser.NullContext context);
}
} // namespace analyzer
